# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Timestamped" do
    optional :created_at, :message, 1, "google.protobuf.Timestamp"
  end
  add_message "Sequential" do
    optional :seq, :int64, 1
  end
end

Timestamped = Google::Protobuf::DescriptorPool.generated_pool.lookup("Timestamped").msgclass
Sequential = Google::Protobuf::DescriptorPool.generated_pool.lookup("Sequential").msgclass
